name: Triggered Workflow with Various Inputs

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - dev
      - main
  workflow_dispatch:
    inputs:
      run-tests:
        description: "Run tests?"
        type: boolean
        required: true
      test-type:
        description: "Type of tests to run"
        type: choice
        options:
          - unit
          - integration
          - all
        required: true
      environment:
        description: "Choose an environment"
        type: choice
        options:
          - dev
          - qa
          - prod
        required: true
      build-number:
        description: "Custom build number"
        type: number
        required: false
      message:
        description: "Additional message"
        type: string
        required: false

jobs:
  build-and-deploy:
    environment: ${{ github.base_ref }}
    runs-on: ubuntu-latest
    steps:
      # Get inputs from workflow_dispatch
      - name: Print workflow inputs
        run: |
          echo "Run tests: ${{ inputs.run-tests }}"
          echo "Test type: ${{ inputs.test-type }}"
          echo "Environment: ${{ inputs.environment }}"
          echo "Build number: ${{ inputs.build-number }}"
          echo "Message: ${{ inputs.message }}"

      # Perform actions based on inputs
      - name: Run tests (if selected)
        if: ${{ inputs.run-tests == true }}
        run: |
          echo "Running tests of type: ${{ inputs.test-type }}"

  deploy-dev:
    runs-on: 'ubuntu-latest'
    environment: 'dev'
    needs: build-and-deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.2"